image: python:latest

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
    paths:
        - .cache/pip
        - venv/

before_script:
    - python -V
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements-dev.txt
    - pip install -e .

stages:
    - build
    - test
    - publish

build:
    stage: build
    script:
        - python -m build
    artifacts:
        paths:
            - dist/*.whl

test:
    stage: test
    needs: []
    script:
        - pytest --cov=iqtrade
        - mypy iqtrade examples tests
        - flake8 iqtrade examples tests
        - black --diff --check iqtrade tests examples
        - codecov

publish:
    stage: publish
    only:
        - tags
    needs: ["build"]
    script:
        - pip install twine
        - python -m twine upload dist/*
    when: manual
